name: Python CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -r requirements.txt

      - name: Unit tests
        run: |
          source .venv/bin/activate
          pytest -q tests/test_health.py

      - name: API smoke (SQLite)
        run: |
          source .venv/bin/activate
          export DATABASE_URL=sqlite:///./dev.db
          rm -f dev.db || true
          nohup python -m uvicorn backend.app:app --host 0.0.0.0 --port 8000 > server.log 2>&1 &
          python - <<'PY'
          import time, requests, sys
          ok=False
          for _ in range(60):
              try:
                  h=requests.get("http://127.0.0.1:8000/health", timeout=1)
                  if h.status_code==200:
                      print("HEALTH:", h.status_code, h.text); ok=True; break
              except Exception:
                  time.sleep(0.5)
          sys.exit(0 if ok else 1)
          PY
          pkill -f "uvicorn backend.app:app" || true

      - name: Archive server log (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: server-log
          path: server.log
