"""Keyword pack definitions (simple substring hits).

Notes:
- Keep terms lower-case (assumes upstream text is normalized to lower-case).
- Favor multi-word / procurement-idiom phrases to reduce false positives.
- Include hyphen/space variants where they commonly appear in notices/specs.
"""

KEYWORD_PACKS = {
    # Radiological / nuclear / rad safety procurement language
    "radiological": [
        # facilities / equipment
        "glovebox",
        "argon glovebox",
        "inert atmosphere glovebox",
        "hot cell",
        "shielded cell",
        "shielded enclosure",
        "shielded room",
        "shielded door",
        "lead-lined",
        "lead lined",
        "lead shielding",
        "neutron shielding",
        "gamma shielding",
        "x-ray shielding",
        "borated polyethylene",
        "high density concrete",
        "tungsten shielding",
        # operations / safety programs
        "health physics",
        "radiation protection",
        "radiation safety",
        "radiological control",
        "radiological controls",
        "contamination control",
        "decontamination",
        "dosimetry",
        "personnel dosimetry",
        "radiation survey",
        "survey meter",
        "wipe test",
        "smear test",
        "portal monitor",
        "whole body counter",
        # materials / licensing-ish language that shows up in buys
        "radioactive material",
        "sealed source",
        "unsealed source",
        "byproduct material",
        "source material",
        "special nuclear material",
        "fissile material",
        "criticality safety",
        "material control and accountability",
        "mc&a",
        # common isotopes/materials
        "tritium",
        "uranium",
        "plutonium",
        "radioisotope",
        "isotope production",
        # CFR strings that appear verbatim in SOW/specs (keep as phrases)
        "10 cfr 20",
        "10 cfr 30",
        "10 cfr 70",
        "10 cfr 71",
        "10 cfr 73",
        "10 cfr 74",
        "10 cfr 835",
    ],

    # Secure areas / classified build language
    "secure_areas": [
        "special access program facility",
        "top secret/sci",
        "dd254",
        "need-to-know",
        "classified processing",
        "classified information",
        "closed area",
        "open storage area",
        "secure vault",
        "gsa class 5",
        "class 5 vault",
        # accreditation / guidance that often rides along with procurements
        "jsig",
        "joint special access program implementation guide",
    ],

    # Shielding / EMSEC / TEMPEST / RF-hardening (often co-occurs with SCIF work)
    "shielding_emsec": [
        "tempest",
        "emsec",
        "emission security",
        "rf shielding",
        "rf shielded",
        "emi shielding",
        "electromagnetic shielding",
        "faraday cage",
        "shielded enclosure",
        "shielded room",
        "waveguide",
        "honeycomb vent",
        "shielded penetration",
        "acoustic attenuation",
        "sound attenuation",
        "acoustic treatment",
    ],

    # Physical security systems & access control procurement language
    "access_control": [
        "physical access control system",
        "access control system",
        "badge reader",
        "card reader",
        "credential reader",
        "biometric access",
        "fingerprint reader",
        "iris scanner",
        "two-factor access",
        "mantrap",
        "turnstile",
        "door controller",
        "electric strike",
        "magnetic lock",
        "mag lock",
        "security vestibule",
        "intercom",
        "video intercom",
        "cctv",
        "video surveillance",
        "security camera",
        "intrusion detection system",
        "alarm monitoring",
        "duress alarm",
        # common federal identity/access phrasing
        "hspd-12",
        "piv card",
        "fips 201",
        "common access card",
        "cac card",
    ],

    # Controlled environments (cleanroom / pressure regimes / filtration)
    "controlled_environments": [
        "cleanroom",
        "clean room",
        "iso class",
        "gowning",
        "gowning room",
        "air shower",
        "airlock",
        "anteroom",
        "ante-room",
        "pressure cascade",
        "negative pressure",
        "positive pressure",
        "hepa filtration",
        "hepa filter",
        "ulpa filter",
        "laminar flow",
        "vibration isolation",
        "humidity control",
        "dew point control",
        "temperature stability",
        "dry room",
        "nitrogen purge",
        "inert atmosphere",
    ],

    # Facilities construction / build-out language (keep it “project-ish” not generic)
    "facilities_construction": [
        "design-build",
        "design build",
        "renovation",
        "build-out",
        "build out",
        "fit-out",
        "fit out",
        "facility upgrade",
        "facility modernization",
        "room build",
        "secure room build",
        "scif build-out",
        "scif build out",
        "shielding installation",
        "rf shielding installation",
        "commissioning",
        "testing adjusting and balancing",
        "hvac upgrade",
        "mechanical upgrade",
        "electrical upgrade",
        "uninterruptible power supply",
        "backup generator",
        "raised floor",
        "pre-action sprinkler",
        "clean agent suppression",
        "novec 1230",
        "fm-200",
    ],

    # Aerospace / EW / signatures (fixes your comma bug and adds procurement-style terms)
    "aerospace": [
        "hypersonic",
        "scramjet",
        "ramjet",
        "rocket-based combined cycle",
        "low observable",
        "radar cross section",
        "signature management",
        "stealth",
        "sigint",
        "elint",
        "comint",
        "jamming",
        "jammer",
        "electronic warfare",
        "electronic attack",
        "electronic protection",
        "electronic support",
        "directed energy",
        "high power microwave",
        "counter-uas",
        "counter unmanned aircraft",
    ],
}
